function FSA_LW76_rip

% read through ROI files generated by Jeff's old script, and extract the data with the filenames


mov_listing=dir(fullfile(pwd,'*.mat'));
mov_listing={mov_listing(:).name};
filenames=mov_listing;




for i=1:length(mov_listing)

     [path,file,ext]=fileparts(filenames{i});
	         load(fullfile(pwd,mov_listing{i}),'align_detrended','align_frame_idx', 'align_mic_data', 'align_raw','movie_fs','padding','rois','TEMPLATE');  %load movie data

S = filenames{i}(1:end-4);



Dat.Align_detrend{i} = align_detrended;
Dat.Align_frame_idx{i} = align_frame_idx;
Dat.Align_mic_data{i} = align_mic_data;
Dat.Align_raw{i} = align_raw;
Dat.Filenames{i} = S;
Dat.Movie_fs = movie_fs;
Dat.Padding = padding;
Dat.ROIs = rois;
Dat.Template = TEMPLATE;


end

save('ROI_Data_LW76.mat','Dat');